### ISSUE TITLE
Zamanlıyıcı İçin Ufak Eklemeler

### ISSUE THREAD

**Issue by emirpolatt** [ozcaan11/python_mini_projeler#2]
" Hocam merhabalar. Zamanlıyıcı projesi için eklediğim bir kaç satır kod. Zamanlıyıcı artık 1 kere gösterip bırakmıyor, her saniye ilerliyor "

import time 

while True:
    zaman = time.localtime()
    
    yil = zaman[1]
    ay = zaman[1]
    gun = zaman[2]
    saat = zaman[3]
    dakika = zaman[4]
    saniye = zaman[5]

    time.sleep(1)
    print("""
    tarih: {}/{}/{}
    saat : {}:{}:{}
    """.format(gun, ay, yil, saat, dakika, saniye))

**Comment by ozcanyarimdunya** [comment]
Tesekkurler ekledim
https://github.com/ozcanyarimdunya/python_mini_projeler/commit/d0b9d5baa74a0cd5a4aade8efd9dd608dc2404ae

**Comment by emirpolatt** [comment]
Ben teşekkür ederim. Daha bu mecralarda yeniyim. İlk defa issues felan açtım anlamışsımızdır acemiliğimi kusura bakmayın 😊

Gönderen Outlook<http://aka.ms/weboutlook>
________________________________
Gönderen: Özcan Yarımdunya <notifications@github.com>
Gönderildi: 6 Ocak 2019 Pazar 21:12
Kime: ozcanyarimdunya/python_mini_projeler
Bilgi: Emir Polat; Author
Konu: Re: [ozcanyarimdunya/python_mini_projeler] Zamanlıyıcı İçin Ufak Eklemeler (#2)


Tesekkurler ekledim
d0b9d5b<https://github.com/ozcanyarimdunya/python_mini_projeler/commit/d0b9d5baa74a0cd5a4aade8efd9dd608dc2404ae>

**Comment by ozcanyarimdunya** [comment]
Hic sorun degil Ben tesekkur ederim 😀

**Comment by alganbarlas** [comment]
Hocam mail dışında iletişim kurabileceğimiz bir mecra var mı  başka ? 😊

Gönderen Outlook<http://aka.ms/weboutlook>
________________________________
Gönderen: Özcan Yarımdunya <notifications@github.com>
Gönderildi: 6 Ocak 2019 Pazar 21:35
Kime: ozcanyarimdunya/python_mini_projeler
Bilgi: Emir Polat; Author
Konu: Re: [ozcanyarimdunya/python_mini_projeler] Zamanlıyıcı İçin Ufak Eklemeler (#2)


Hic sorun degil Ben tesekkur ederim 😀
